### ISSUE TITLE
Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

### ISSUE THREAD

**Issue by gkucmierz** [katharinakoal/ngx-qrcode-svg#2]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Not working with Ivy

## Expected behavior

Working

## Environment

<pre><code>
Angular CLI: 10.0.0
Node: 14.4.0
OS: darwin x64

Angular: 10.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/cdk                      10.0.0
@angular/cli                      10.0.0
@angular/material                 10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
</code></pre>

```
    ERROR in node_modules/ngx-qrcode-svg/lib/ngx-qrcode-svg.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (ngx-qrcode-svg) which declares QRCodeSVGModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

**Comment by katharinakoal** [comment]
Thanks for reaching out @gkucmierz !
Unfortunately, I couldn't reproduce this error with a fresh install of angular 10. However, this seems to be a common problem if you recently upgraded your angular project, and something went wrong along the way.
You can enforce the ivy compatibility compiler to run after every install by adding this script to your `packacke.json` file:
```
{
  "scripts": {
    "postinstall": "ngcc"
  }
}
```
After that, run `npm install` again, and it should build the ivy-compatible versions of your libraries.
Please let me know if this solves this problem.
